### PR TITLE
Patch codecov config

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Comment by webknjaz** [comment]
Maybe turn it into a draft?

**Comment by ssbarnea** [comment]
Github does not yet allow undrafting like gerrit.

**Comment by webknjaz** [comment]
> Github does not yet allow undrafting like gerrit.

What do you mean by that?

**Comment by ssbarnea** [comment]
@webknjaz Do you have any idea why `codecov/patch` check is still reporting with this change. My expectation was to see only `codecov/project` one but both are still there. Based on their docs this should disable it.

**Comment by webknjaz** [comment]
No idea

**Pull request merged**
